version: '2.0'

services:
  albagen: 
    image: albagen:latest
    environment:
    - ALBATROSS_NODES=http://seed1.nimiq.local:8648,http://seed2.nimiq.local:8648,http://seed3.nimiq.local:8648,http://seed4.nimiq.local:8648
    - SEED_WALLET_ADDRESS=NQ87 HKRC JYGR PJN5 KQYQ 5TM1 26XX 7TNG YT27
    - SEED_WALLET_PRIVATE_KEY=3336f25f5b4272a280c8eb8c1288b39bd064dfb32ebc799459f707a0e88c4e5f
    - NEW_ACCOUNT_MIN_NIM=100
    - NEW_ACCOUNT_MAX_NIM=1000
    - STAKERS_TO_CREATE=500
    volumes:
    - albagen_data:/data
    network_mode: host

volumes:
  albagen_data:
